spring.thymeleaf.cache=false

# Quan tr?ng!
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-morning-rice-a1eo44sh-pooler.ap-southeast-1.aws.neon.tech:5432/thi_hanh_an?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VPj1gdN0qRhH

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# gcloud projects create excel2word-project2
# gcloud config set project excel2word-project2
# enable API :
# gcloud services enable run.googleapis.com
# gcloud services enable artifactregistry.googleapis.com
# gcloud services enable cloudbuild.googleapis.com
# gcloud artifacts repositories create excel2word-repo  --repository-format=docker  --location=asia-southeast1
# ====================================
# 1. Build images using Cloud Build
# ====================================
#gcloud builds submit --project=excel2word-project2 --tag asia-southeast1-docker.pkg.dev/excel2word-project2/excel2word-repo/excel2word-app

# ====================================
# 2. Deploy to Cloud Run
# ====================================
#gcloud run deploy excel2word-app --image asia-southeast1-docker.pkg.dev/excel2word-project2/excel2word-repo/excel2word-app --region=asia-southeast1 --platform=managed --allow-unauthenticated --project=excel2word-project2

# ====================================
# 3. Configure Cloud Run to reduce costs
# ====================================
#gcloud run services update excel2word-app --min-instances=0 --max-instances=2 --cpu-throttling --project=excel2word-project2 --region=asia-southeast1


# 4. Full list of services you can safely disable
#    gcloud services disable bigquery.googleapis.com --force
#    gcloud services disable bigquerystorage.googleapis.com --force
#    gcloud services disable compute.googleapis.com --force   \
#    # if not using VM
#    gcloud services disable container.googleapis.com --force \
#    # if not using Kubernetes
#    gcloud services disable spanner.googleapis.com --force
#    gcloud services disable firestore.googleapis.com --force
#    gcloud services disable sqladmin.googleapis.com --force  \
#    # if not using Cloud SQL
#    gcloud services disable dataproc.googleapis.com --force
#    gcloud services disable dataflow.googleapis.com --force
#    gcloud services disable pubsub.googleapis.com --force    \
#    # if not using Pub/Sub
#    gcloud services disable monitoring.googleapis.com --force
#    gcloud services disable notebook.googleapis.com --force

# gcloud run revisions delete REVISION_NAME --project=excel2word-project2 --region=asia-southeast1

# check running image + deletable image
# gcloud run revisions list --region=asia-southeast1 --project=excel2word-project2
